### ISSUE TITLE
Users: Setup Connection To SQLite Database

### ISSUE THREAD

**Issue by rscottlundgren** [rscottlundgren/hyrule-gis-api#15]
### Tasks (Complete in Top to Bottom Order)
- [x] https://github.com/rscottlundgren/hyrule-gis-api/issues/10
- [x] https://github.com/rscottlundgren/hyrule-gis-api/issues/11
- [x] https://github.com/rscottlundgren/hyrule-gis-api/issues/12
- [x] https://github.com/rscottlundgren/hyrule-gis-api/issues/13
- [x] https://github.com/rscottlundgren/hyrule-gis-api/issues/14
