### ISSUE TITLE
Feat: Coordinates - Setup Connection To SQLite Database

### ISSUE THREAD

**Issue by rscottlundgren** [rscottlundgren/hyrule-gis-api#20]
### Tasks to Complete (in Top to Bottom Order):
- [x] https://github.com/rscottlundgren/hyrule-gis-api/issues/16
- [x] https://github.com/rscottlundgren/hyrule-gis-api/issues/17
- [x] https://github.com/rscottlundgren/hyrule-gis-api/issues/18
- [x] https://github.com/rscottlundgren/hyrule-gis-api/issues/19
