### ISSUE TITLE
Feat: Materials - Setup Connection To SQLite Database

### ISSUE THREAD

**Issue by rscottlundgren** [rscottlundgren/hyrule-gis-api#25]
### Tasks to Complete (in Top to Bottom Order):
- [x] https://github.com/rscottlundgren/hyrule-gis-api/issues/21
- [x] https://github.com/rscottlundgren/hyrule-gis-api/issues/22
- [x] https://github.com/rscottlundgren/hyrule-gis-api/issues/23
- [x] https://github.com/rscottlundgren/hyrule-gis-api/issues/24
